apiVersion: v1
kind: Service
metadata:
  name: employee-details-backend-service
  namespace: employee-details
  labels:
    app: employee-details-backend
spec:
  type: ClusterIP
  selector:
    app: employee-details-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None 