apiVersion: v1
kind: Secret
metadata:
  name: employee-details-secret
  namespace: employee-details
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXlvdXItc2VjcmV0LWtleS1oZXJlLWNoYW5nZS1pbi1wcm9kdWN0aW9u
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM= 